export const COLORS = [
  "#a78bfa",
  "#22d3ee",
  "#f5c542",
  "#f87171",
  "#34d399",
  "#f472b6",
  "#60a5fa",
  "#fb923c",
  "#c084fc",
  "#2dd4bf",
  "#e879f9",
  "#4ade80",
];

export const MIN_BET = 0.25;
export const START_BALANCE = 10;
export const SPIN_DURATION_MS = 4200;
export const SPIN_FINISH_DELAY_MS = 4500;
export const MAX_PLAYERS = 10;
export const BOT_USERNAME = "Gramelle_bot";
export const ROUND_COUNTDOWN_SEC = 20;

/**
 * Economy
 * - 1 TON = 1 GRAM
 * - 500 Stars = 4.25 GRAM → 0.0085 GRAM/Star
 * - House edge 5% of bank → winner gets 95%
 * - Min deposit 0.5 GRAM, min withdraw 5 GRAM, withdraw fee 0.2 GRAM
 */
export const GRAM_PER_STAR =
  Number(process.env.NEXT_PUBLIC_GRAM_PER_STAR) || 0.0085;
export const GRAM_PER_TON =
  Number(process.env.NEXT_PUBLIC_GRAM_PER_TON) || 1;

export const HOUSE_EDGE = 0.05; // 5%

export const MIN_DEPOSIT_GRAM = 0.5;
export const MIN_DEPOSIT_STARS = Math.ceil(0.5 / 0.0085); // ~59
export const MAX_DEPOSIT_STARS = 10_000_000; // effectively unlimited
export const MIN_DEPOSIT_TON = 0.5;
export const MAX_DEPOSIT_TON = 1_000_000; // effectively unlimited

export const MIN_WITHDRAW_TON = 5;
export const MAX_WITHDRAW_TON = 1_000_000; // effectively unlimited
export const WITHDRAW_FEE_GRAM = 0.2;

/** Join bonus for inviting a brand-new user */
export const REFERRAL_JOIN_BONUS = 0.25;

/**
 * Referral tiers — % of HOUSE COMMISSION generated by active referrals' bets.
 * Active = referral has at least 1 game.
 * Turnover = sum of absolute bet amounts by referrals.
 */
export type ReferralTierId = "none" | "bronze" | "silver" | "gold" | "platinum";

export interface ReferralTier {
  id: ReferralTierId;
  name: string;
  minActive: number;
  maxActive: number | null;
  minTurnover: number;
  shareOfHouseFee: number; // e.g. 0.10 = 10% of house fee from ref bets
  color: string;
  emoji: string;
}

export const REFERRAL_TIERS: ReferralTier[] = [
  {
    id: "bronze",
    name: "Bronze",
    minActive: 1,
    maxActive: 9,
    minTurnover: 0,
    shareOfHouseFee: 0.1,
    color: "#cd7f32",
    emoji: "🥉",
  },
  {
    id: "silver",
    name: "Silver",
    minActive: 10,
    maxActive: 49,
    minTurnover: 500,
    shareOfHouseFee: 0.15,
    color: "#c0c0c0",
    emoji: "🥈",
  },
  {
    id: "gold",
    name: "Gold",
    minActive: 50,
    maxActive: 99,
    minTurnover: 2500,
    shareOfHouseFee: 0.2,
    color: "#f5c542",
    emoji: "🥇",
  },
  {
    id: "platinum",
    name: "Platinum",
    minActive: 100,
    maxActive: null,
    minTurnover: 10_000,
    shareOfHouseFee: 0.25,
    color: "#a78bfa",
    emoji: "💎",
  },
];

export function getReferralTier(
  activeRefs: number,
  turnover: number
): ReferralTier | null {
  if (activeRefs < 1) return null;
  // Highest tier that fully qualifies
  for (const t of [...REFERRAL_TIERS].reverse()) {
    if (activeRefs >= t.minActive && turnover >= t.minTurnover) {
      return t;
    }
  }
  return null;
}

export type StarPackage = {
  stars: number;
  gram: number;
  label: string;
  popular?: boolean;
  bonus?: string;
};

export const STAR_PACKAGES: StarPackage[] = [
  { stars: 100, gram: 0.85, label: "100" },
  { stars: 250, gram: 2.125, label: "250" },
  { stars: 500, gram: 4.25, label: "500", popular: true },
  { stars: 1000, gram: 8.5, label: "1000", bonus: "×2" },
];

export type TonPackage = {
  ton: number;
  gram: number;
  label: string;
  popular?: boolean;
  bonus?: string;
};

export const TON_PACKAGES: TonPackage[] = [
  { ton: 0.5, gram: 0.5, label: "0.5" },
  { ton: 1, gram: 1, label: "1" },
  { ton: 5, gram: 5, label: "5", popular: true },
  { ton: 10, gram: 10, label: "10" },
  { ton: 25, gram: 25, label: "25" },
];

export const TON_DEPOSIT_ADDRESS =
  process.env.NEXT_PUBLIC_TON_WALLET ||
  "UQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJKZ";

/** Hot wallet for player reserves (liability) — env */
export const TON_RESERVE_WALLET =
  process.env.NEXT_PUBLIC_TON_RESERVE_WALLET || TON_DEPOSIT_ADDRESS;
/** Project profit wallet — env */
export const TON_PROFIT_WALLET =
  process.env.NEXT_PUBLIC_TON_PROFIT_WALLET || TON_DEPOSIT_ADDRESS;

export type RoomMode = "classic" | "high";

export interface RoomConfig {
  id: RoomMode;
  name: string;
  description: string;
  minBet: number;
  maxBet: number;
  houseEdge: number;
  maxPlayers: number;
  countdownSec: number;
}

export const ROOMS: Record<RoomMode, RoomConfig> = {
  classic: {
    id: "classic",
    name: "Classic",
    description: "Standard stakes",
    minBet: 0.25,
    maxBet: 500,
    houseEdge: HOUSE_EDGE,
    maxPlayers: 10,
    countdownSec: 20,
  },
  high: {
    id: "high",
    name: "High",
    description: "Higher stakes",
    minBet: 10,
    maxBet: 5000,
    houseEdge: HOUSE_EDGE,
    maxPlayers: 8,
    countdownSec: 20,
  },
};


/** Anti-abuse */
export const MAX_PENDING_WITHDRAWALS = 3;
export const MAX_BETS_PER_MINUTE = 20;
/** Max TON withdrawn per telegram user per UTC day */
export const DAILY_WITHDRAW_LIMIT_TON = 50;
export const MIN_BANK_TO_SPIN = 0.5; // classic soft floor for UX messaging

export const DEFAULT_ROOM: RoomMode = "classic";
